version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: movies-catalog-db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/data/postgres
  redis-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - ${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-cache:/data
volumes:
  postgres:
    driver: local
  redis-cache:
    driver: local
