version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: movies-catalog-db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
    driver: local
